# Generated by Django 4.2.6 on 2023-10-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_resetpassword_usertoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
