# Generated by Django 4.2.6 on 2023-10-31 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0002_rename_providedlinks_links"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Links",
            new_name="Link",
        ),
    ]
