# Generated by Django 4.2.6 on 2023-11-01 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("links", "0007_linkcategories_link_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seller_status",
                    models.CharField(
                        choices=[
                            ("NS", "Not Specified"),
                            ("A", "Accept"),
                            ("R", "Reject"),
                            ("PC", "Price Changed"),
                            ("P", "Paied"),
                        ],
                        default="NS",
                        max_length=2,
                    ),
                ),
                (
                    "buyer_status",
                    models.CharField(
                        choices=[
                            ("NS", "Not Specified"),
                            ("A", "Accept"),
                            ("R", "Reject"),
                            ("PC", "Price Changed"),
                            ("P", "Paied"),
                        ],
                        default="NS",
                        max_length=2,
                    ),
                ),
                ("initial_price", models.BigIntegerField(default=0)),
                ("updated_price", models.BigIntegerField(default=0)),
                ("proposed_title", models.CharField(max_length=255)),
                ("proposed_content", models.TextField()),
                ("backlink", models.CharField(max_length=255)),
                ("anchor_text", models.CharField(max_length=255)),
                (
                    "proposed_meta_title",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "proposed_meta_description",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_submited", models.BooleanField(default=False)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="links.link"
                    ),
                ),
                (
                    "link_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="links.linkprovider",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
