# Generated by Django 4.2.6 on 2023-11-04 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0010_link_created_at_link_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="linkcategories",
            name="link_provider",
        ),
    ]
