# Generated by Django 4.2.6 on 2023-11-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0011_remove_linkcategories_link_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkcategories",
            name="link",
            field=models.ManyToManyField(to="links.link"),
        ),
    ]
