# Generated by Django 4.2.6 on 2023-11-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0012_alter_linkcategories_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkcategories",
            name="link",
            field=models.ManyToManyField(related_name="link", to="links.link"),
        ),
    ]
