# Generated by Django 4.2.6 on 2023-11-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0014_alter_link_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
