# Generated by Django 4.2.6 on 2023-11-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0015_alter_link_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="linkcategories",
            name="link",
        ),
        migrations.AddField(
            model_name="link",
            name="categories",
            field=models.ManyToManyField(
                related_name="categories", to="links.linkcategories"
            ),
        ),
    ]
