# Generated by Django 4.2.7 on 2023-11-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0017_delete_linkrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkprovider',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
