# Generated by Django 4.2.6 on 2023-11-08 07:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0017_delete_linkrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LinkRequest",
            new_name="LinkOrder",
        ),
    ]
