# Generated by Django 4.2.6 on 2023-11-08 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_rename_linkrequest_linkorder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="linkorder",
            name="link",
        ),
        migrations.RemoveField(
            model_name="linkorder",
            name="seller_status",
        ),
    ]
