# Generated by Django 4.2.6 on 2023-11-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_remove_linkorder_link_remove_linkorder_seller_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="linkorder",
            name="seller",
        ),
        migrations.AddField(
            model_name="linkorder",
            name="seller_status",
            field=models.CharField(
                choices=[
                    ("NS", "Not Specified"),
                    ("A", "Accept"),
                    ("R", "Reject"),
                    ("PC", "Price Changed"),
                    ("P", "Paied"),
                ],
                default="NS",
                max_length=2,
            ),
        ),
    ]
